PRAGMA foreign_keys=ON;

CREATE TABLE IF NOT EXISTS "User" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "username" TEXT UNIQUE,
  "name" TEXT NOT NULL,
  "studentId" TEXT NOT NULL UNIQUE,
  "className" TEXT,
  "phone" TEXT,
  "email" TEXT,
  "passwordHash" TEXT NOT NULL,
  "role" TEXT NOT NULL DEFAULT 'USER',
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "approvalStatus" TEXT NOT NULL DEFAULT 'APPROVED',
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Book" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "title" TEXT NOT NULL,
  "author" TEXT,
  "publisher" TEXT,
  "category" TEXT,
  "isbn" TEXT,
  "description" TEXT,
  "sourceType" TEXT NOT NULL DEFAULT 'ORIGINAL',
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "BookCopy" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "bookId" INTEGER NOT NULL,
  "copyCode" TEXT NOT NULL UNIQUE,
  "status" TEXT NOT NULL DEFAULT 'AVAILABLE',
  "location" TEXT,
  "qrCodeUrl" TEXT,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "BookCopy_bookId_fkey" FOREIGN KEY ("bookId") REFERENCES "Book" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "BorrowRecord" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "userId" INTEGER NOT NULL,
  "bookCopyId" INTEGER NOT NULL,
  "borrowedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "dueAt" DATETIME,
  "returnedAt" DATETIME,
  "status" TEXT NOT NULL DEFAULT 'BORROWED',
  CONSTRAINT "BorrowRecord_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "BorrowRecord_bookCopyId_fkey" FOREIGN KEY ("bookCopyId") REFERENCES "BookCopy" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "AuditLog" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "userId" INTEGER,
  "action" TEXT NOT NULL,
  "targetType" TEXT,
  "targetId" TEXT,
  "detail" TEXT,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "BookCopy_bookId_idx" ON "BookCopy"("bookId");
CREATE INDEX IF NOT EXISTS "BorrowRecord_userId_idx" ON "BorrowRecord"("userId");
CREATE INDEX IF NOT EXISTS "BorrowRecord_bookCopyId_idx" ON "BorrowRecord"("bookCopyId");
